refactored e3e test for allure report persistence

diff --git a/employee/Jenkinsfile b/employee/Jenkinsfile
--- a/employee/Jenkinsfile
+++ b/employee/Jenkinsfile
@@ -81,7 +81,7 @@ pipeline {
         //         }
         //     }
         // }
-        stage('Integration Tests') {
+        stage('E2E Tests') {
             when {
                 expression { params.TEST_MODE == true }
             }
@@ -103,6 +103,18 @@ pipeline {
             post {
                 always {
                     dir('employee') {
+                        // Extract artifacts before tear down
+                        sh """
+                        CONTAINER_ID=\$(docker compose -f docker-compose-v2.yml ps -q behave-tests)
+                        if [ ! -z "\$CONTAINER_ID" ]; then
+                            echo "Copying artifacts from \$CONTAINER_ID..."
+                            mkdir -p allure-results test-results
+                            docker cp \$CONTAINER_ID:/employee/allure-results/. allure-results/ || true
+                            docker cp \$CONTAINER_ID:/employee/test-results/. test-results/ || true
+                        else
+                            echo "Container not found, skipping artifact copy."
+                        fi
+                        """
                         sh "docker compose -f docker-compose-v2.yml down -v"
                     }
 
